name: Builder

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install cmake g++ libjsoncpp-dev libsqlite3-dev
        sudo apt install ./github/files/libpistache0.deb ./github/files/libpistache-dev.deb
    - name: Building
      run: |
        mkdir build
        cd build
        cmake ..
        make
